### ISSUE TITLE
Final Capstone KanbanBoard

### ISSUE THREAD

**Issue by PowerLevel9000** [enis-memic/booking_app_api#23]
# Final Capstone KanbanBoard

team of 4 @Habtamu210 @ernestmusong @enis-memic @PowerLevel9000 

project link => https://github.com/enis-memic/booking_app_api/projects/2

SS => 
![image](https://github.com/enis-memic/booking_app_api/assets/116451144/b56bad7f-8041-4dac-a63e-1a2a12350778)

## Project setup

Task distributed according to the time, points, frontend, and backend
- Frontend team @ernestmusong @PowerLevel9000 
- backend team @Habtamu210 @enis-memic 

## Happy developing 

![SiEnchufeTvGIF](https://github.com/enis-memic/booking_app_api/assets/116451144/b05c973f-d065-4873-82d5-59fd096bb81b)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- Equitable distribution of tasks/issues 👍 
- All issues have great descriptions with clear breakdowns 👍 
- Your issues seem to cover all functional requirements of project 👍 

## Optional suggestions
- [OPTIONAL] Consider adding labels to your issues, it makes it easier to filter by different types and gives another added level of differentiation among tasks (front-end vs back-end etc.)

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PowerLevel9000** [comment]
# Thank you 💪💪💪🙏🙏🙏

![ThankYouSoMuchPrabhasGIF](https://user-images.githubusercontent.com/116451144/233258767-f3943ca4-fbe2-4fde-b8b1-2129593266e5.gif)


hi @mcrd25 ,

sure we will consider the labeling 

I wanted to express my gratitude for your willingness to take the time to review my code on GitHub. Your feedback and suggestions have been instrumental in improving the quality of my work, and I appreciate your insights and expertise in this area.

It's inspiring to have someone like you, who is knowledgeable and experienced, provide valuable feedback that helps me enhance my coding skills. I truly appreciate the time and effort you put into reviewing my code, and I'm grateful for your constructive criticism.

If there are any areas that I need to work on, please don't hesitate to let me know. I'm open to hearing any suggestions or recommendations you may have. Your feedback is essential to my growth as a developer, and I value it tremendously.

Thank you again for your time and for sharing your expertise with me. I'm looking forward to applying the insights gained from your review to my future projects.

Sincerely,
@PowerLevel9000
